services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
        - PUBLIC_REST_API_URL=${PUBLIC_REST_API_URL}
    env_file:
      - .env
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=5173
      - ORIGIN=${WEB_APP_ORIGIN:-http://localhost:5173}
      - REST_API_URL=http://rest-api-app-1:8080/api/v1
    networks:
      - cardmesh

networks:
  cardmesh:
    external: true
